### ISSUE TITLE
Undefined symbol for architecture armv7

### ISSUE THREAD

**Issue by Frobei** [keyv/iOSUnityVuforiaGuide#13]
I followed step by step and I got this error when I try to build the project on a device:

> Undefined symbols for architecture armv7: "_MTAudioProcessingTapGetSourceAudio", referenced from: AVFoundationVideoPlayback::PlayerPriv::ProcessAudioTap(opaqueMTAudioProcessingTap const*, long, unsigned int, AudioBufferList*, long*, unsigned int*) in libiPhone-lib.a(AVFoundationVideoPlayback.o) "_MTAudioProcessingTapCreate", referenced from: -[AVFoundationMediaLoader ConfigureAudioOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o) "_MTAudioProcessingTapGetStorage", referenced from: -[AVFoundationMediaLoader ConfigureAudioOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o) AVFoundationVideoPlayback::PlayerPriv::PrepareAudioTap(opaqueMTAudioProcessingTap const*, long, AudioStreamBasicDescription const*) in libiPhone-lib.a(AVFoundationVideoPlayback.o) AVFoundationVideoPlayback::PlayerPriv::ProcessAudioTap(opaqueMTAudioProcessingTap const*, long, unsigned int, AudioBufferList*, long*, unsigned int*) in libiPhone-lib.a(AVFoundationVideoPlayback.o) AVFoundationVideoPlayback::PlayerPriv::FinalizeAudioTap(opaqueMTAudioProcessingTap const*) in libiPhone-lib.a(AVFoundationVideoPlayback.o) -[AVFoundationMediaLoader StopOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o) ld: symbol(s) not found for architecture armv7 clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm using Unity 5.6.0f3 and Xcode 8.1.
Is there someone who encountered the same issue and managed to avoid it ?

**Comment by Balaji-Rahunathan** [comment]
add mediatoolbox framework
