### ISSUE TITLE
Black background instead of Vuforia camera feed

### ISSUE THREAD

**Issue by cxvii** [keyv/iOSUnityVuforiaGuide#4]
Hi, i followed your steps and tried multiple times to integrate a sample Unity + Vuforia app in iOS. Every time what i get is the app working fine, tracking image targets works and 3d models are correctly displayed, but the scene's background is black.
My environment is Unity 5.3.5f1 and Vuforia 5.9.9. 
Any idea of what's wrong?

**Comment by slfsvrgn** [comment]
Make sure web cam disable play mode is checked?

**Comment by keyv** [comment]
In Unity Player Settings : Other Settings find the Rendering part, uncheck the Auto Graphics API and select only OpenGLES2  and rebuild your unity project.

**Comment by cxvii** [comment]
Thanks keyv, already tried that.
I followed the guide step by step, got the black screen, deleted everything and starter again for three times. 
Still no luck :(
I am building my unity project in release mode, symlink unchecked
if i run the generated ios project everything works perfectly, but when i try to integrate it in a native ios project i get the black screen
I am using an iPad 4 mini running ios 9.3.2

**Comment by cxvii** [comment]
i found the problem:
in unity, under player settings -> other settings -> rendering you have to uncheck auto graphics api, select Metal from the list and remove it with the - button.
i mistakenly thought that selecting opengles2 would suffice
