### ISSUE TITLE
IL2CPP Error

### ISSUE THREAD

**Issue by mimminito** [keyv/iOSUnityVuforiaGuide#5]
Getting an issue when I try and build:
Il2CppGenericMethodDefinitions.cpp:1:13: 'il2cpp-config.h' file not found

Any idea why I am getting this?

**Comment by keyv** [comment]
Are you sure you haven't delete libil2cpp folder instead of removing reference?

**Comment by mimminito** [comment]
Nope, definitely still there.

**Comment by mimminito** [comment]
Im now getting another error:

VuforiaRenderDelegate.h:7:9: 'PluginBase/RenderPluginDelegate.h' file not found

**Comment by mimminito** [comment]
Turns out you cannot have spaces in the path name... Any way of adding these in? Special characters?

**Comment by cschellberg95** [comment]
Hey have you figured out a solution for this? I am getting the very same error
Il2CppCompilerCalculateTypeValues_11Table.cpp:1:13: 'il2cpp-config.h' file not found
